import { getJobs } from "../../lib/jobs";
import { isAuthenticated } from "../../lib/auth";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const dynamic = "force-dynamic";
async function login(formData) { "use server"; if (formData.get("password") === process.env.ADMIN_PASSWORD) { const cookieStore = await cookies(); cookieStore.set("opportunity_admin", (await import("../../lib/auth")).sessionCookie().split("=")[1].split(";")[0], { httpOnly: true, sameSite: "lax", maxAge: 28800, path: "/" }); redirect("/admin"); } redirect("/admin?error=1"); }
async function addJob(formData) { "use server"; const { isAuthenticated } = await import("../../lib/auth"); const cookieStore = await cookies(); if (!isAuthenticated(cookieStore)) redirect("/admin"); const { createJob } = await import("../../lib/jobs"); await createJob(Object.fromEntries(formData)); redirect("/admin"); }
async function removeJob(formData) { "use server"; const { isAuthenticated } = await import("../../lib/auth"); const cookieStore = await cookies(); if (!isAuthenticated(cookieStore)) redirect("/admin"); const { deleteJob } = await import("../../lib/jobs"); await deleteJob(formData.get("id")); redirect("/admin"); }
async function logout() { "use server"; const cookieStore = await cookies(); cookieStore.delete("opportunity_admin"); redirect("/admin"); }
export default async function AdminPage({ searchParams }) { const cookieStore = await cookies(); const params = await searchParams; if (!isAuthenticated(cookieStore)) return <main className="admin-wrap"><section className="login-card"><p className="eyebrow">PRIVATE AREA</p><h1>Admin sign in</h1><p>Use the password configured in your environment file.</p><form action={login}><input type="password" name="password" placeholder="Password" required autoFocus />{params.error && <p className="error">Incorrect password. Please try again.</p>}<button className="button">Sign in</button></form></section></main>; const jobs = await getJobs(); return <main className="admin-wrap"><div className="admin-top"><div><p className="eyebrow">ADMIN PANEL</p><h1>Manage job openings</h1></div><form action={logout}><button className="text-button">Sign out</button></form></div><section className="admin-grid"><form action={addJob} className="job-form"><h2>Post a new job</h2><label>Job title<input name="title" required /></label><label>Company<input name="company" required /></label><div className="two"><label>Location<input name="location" placeholder="e.g. Remote, India" required /></label><label>Employment type<input name="type" placeholder="Full-time" required /></label></div><label>Salary (optional)<input name="salary" placeholder="e.g. ₹8–12 LPA" /></label><label>Job description<textarea name="description" required rows="6" /></label><label>Requirements (optional)<textarea name="requirements" rows="5" /></label><label>Application link<input name="applyUrl" type="url" placeholder="https://..." required /></label><button className="button">Publish job</button></form><section className="posted"><h2>Published jobs ({jobs.length})</h2>{jobs.length ? jobs.map(job => <div className="posted-job" key={job.id}><div><strong>{job.title}</strong><span>{job.company} · <a href={`/jobs/${job.slug}`} target="_blank">View page ↗</a></span></div><form action={removeJob}><input type="hidden" name="id" value={job.id}/><button className="delete">Delete</button></form></div>) : <p className="muted">Your published jobs will appear here.</p>}</section></section></main>; }
